### ISSUE TITLE
import error when running src/server.py

### ISSUE THREAD

**Issue by kvu787** [Mestway/CmdReader#2]
### What did you do?

Ran the following bash commands as specified in the README:

```
$ virtualenv envdir
$ . envdir/bin/activate
$ pip install -r requirements.txt
$ python src/server.py
```
### What did you expect to see?

No errors and some print out indicating the server is running.
### What did you see instead?

```
Traceback (most recent call last):
  File "src/server.py", line 16, in <module>
    from apiclient.discovery import build
  File "/Users/kvu/sync/research/nl2sh/CmdReader/envdir/lib/python2.7/site-packages/apiclient/__init__.py", line 18, in <module>
    from googleapiclient import channel
  File "/Users/kvu/sync/research/nl2sh/CmdReader/envdir/lib/python2.7/site-packages/googleapiclient/channel.py", line 63, in <module>
    from googleapiclient import errors
  File "/Users/kvu/sync/research/nl2sh/CmdReader/envdir/lib/python2.7/site-packages/googleapiclient/errors.py", line 26, in <module>
    from oauth2client import util
ImportError: cannot import name util
```

**Comment by todpole3** [comment]
The error doesn't show up on our side.
I think here is a related issue: https://github.com/google/google-api-python-client/issues/270

Have you tried `pip install --upgrade oauth2client`?
